### ISSUE TITLE
First time setup failed and made this repo hard to use from scratch

### ISSUE THREAD

**Issue by guillett** [openfisca/country-template#160]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I followed the readme instructions

### Here is what I expected to happen:

The Github action to finished successfully

### Here is what actually happened:

https://github.com/openfisca/openfisca-nouvelle_caledonie/actions/runs/11855108200

## Context

I identify more as a:

- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by benjello** [comment]
I think it is related to the switch to config using `pyprojet.toml` isn't it @sandcha and @benoit-cty @bonjourmauko ?

**Comment by benoit-cty** [comment]
Hello,
There is no `.flake8` mention in https://github.com/openfisca/openfisca-nouvelle_caledonie/blob/main/first-time-setup.sh#L81 so maybe it has been fixed ?

**Comment by sandcha** [comment]
Unfortunately, it's still an issue (same test of first time setup script [here](https://github.com/sandcha/openfisca-m_retest/actions/runs/12144987053/job/33865607099#step:4:12)). 😞

**Comment by bonjourmauko** [comment]
I took this code added tests, for extension template, thinking on proposing it here. If you have some time to test, there is one bug I javen't had the time yet to solve: https://github.com/openfisca/openfisca-setup-builder/issues/6
